
[functions.brand-dev]
enabled = true
verify_jwt = true
import_map = "./functions/brand-dev/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/brand-dev/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/brand-dev/*.html" ]

[functions.get-postgrid-templates]
enabled = true
verify_jwt = true
import_map = "./functions/get-postgrid-templates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-postgrid-templates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-postgrid-templates/*.html" ]


[functions.user-campaign]
enabled = true
verify_jwt = true
import_map = "./functions/user-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/user-campaign/*.html" ]


[functions.get-postgrid-editor]
enabled = true
verify_jwt = true
import_map = "./functions/get-postgrid-editor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-postgrid-editor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-postgrid-editor/*.html" ]


[functions.open-ai-templates-suggestion]
enabled = true
verify_jwt = true
import_map = "./functions/open-ai-templates-suggestion/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/open-ai-templates-suggestion/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/open-ai-templates-suggestion/*.html" ]


[functions.open-ai-industry-mapping]
enabled = true
verify_jwt = true
import_map = "./functions/open-ai-industry-mapping/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/open-ai-industry-mapping/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/open-ai-industry-mapping/*.html" ]


[functions.create-template-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-template-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-template-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-template-user/*.html" ]

[functions.postgrid-editor-session]
enabled = true
verify_jwt = true
import_map = "./functions/postgrid-editor-session/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/postgrid-editor-session/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/postgrid-editor-session/*.html" ]

[functions.open-ai-post-editor-area]
enabled = true
verify_jwt = true
import_map = "./functions/open-ai-post-editor-area/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/open-ai-post-editor-area/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/open-ai-post-editor-area/*.html" ]

[functions.ai-postcard-generator]
enabled = true
verify_jwt = true
import_map = "./functions/ai-postcard-generator/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-postcard-generator/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-postcard-generator/*.html" ]

[functions.ai-generate-metadata]
enabled = true
verify_jwt = true
import_map = "./functions/ai-generate-metadata/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-generate-metadata/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-generate-metadata/*.html" ]

[functions.ai-postcard-generator-v2]
enabled = true
verify_jwt = true
import_map = "./functions/ai-postcard-generator-v2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-postcard-generator-v2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-postcard-generator-v2/*.html" ]

[functions.fetchBrandCategory]
enabled = true
verify_jwt = true
import_map = "./functions/fetchBrandCategory/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetchBrandCategory/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetchBrandCategory/*.html" ]

[functions.fetch-Brand-Category]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-Brand-Category/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-Brand-Category/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-Brand-Category/*.html" ]

[functions.ai-postcard-v3]
enabled = true
verify_jwt = true
import_map = "./functions/ai-postcard-v3/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-postcard-v3/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-postcard-v3/*.html" ]
