
[functions.brand-dev]
enabled = true
verify_jwt = true
import_map = "./functions/brand-dev/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/brand-dev/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/brand-dev/*.html" ]

[functions.get-postgrid-templates]
enabled = true
verify_jwt = true
import_map = "./functions/get-postgrid-templates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-postgrid-templates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-postgrid-templates/*.html" ]
