
[functions.brand-dev]
enabled = true
verify_jwt = true
import_map = "./functions/brand-dev/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/brand-dev/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/brand-dev/*.html" ]

[functions.get-postgrid-templates]
enabled = true
verify_jwt = true
import_map = "./functions/get-postgrid-templates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-postgrid-templates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-postgrid-templates/*.html" ]


[functions.user-campaign]
enabled = true
verify_jwt = true
import_map = "./functions/user-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/user-campaign/*.html" ]


[functions.get-postgrid-editor]
enabled = true
verify_jwt = true
import_map = "./functions/get-postgrid-editor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-postgrid-editor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-postgrid-editor/*.html" ]


[functions.open-ai-templates-suggestion]
enabled = true
verify_jwt = true
import_map = "./functions/open-ai-templates-suggestion/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/open-ai-templates-suggestion/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/open-ai-templates-suggestion/*.html" ]

[functions.open-ai-industry-mapping]
enabled = true
verify_jwt = true
import_map = "./functions/open-ai-industry-mapping/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/open-ai-industry-mapping/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/open-ai-industry-mapping/*.html" ]
